### ISSUE TITLE
Navbar /team 連結有些使用者會爆掉

### ISSUE THREAD

**Issue by chenyunchen** [sitcon-tw/2020#14]
Navbar link 到 /2020/team
https://sitcon.org/2020/team/ -> 404

使用者 **有時** 點連結不會自動轉址
/2020/team/ -> redirect /2020/team/staff

Team這頁底下分成 `sponsor.html` `staff.html`
爆掉原因是 `Server Side Render` 沒有對應的 `index.html`

看是不是要在 `npm build` 多加
**cp ./dist/2020/team/staff.html ./dist/2020/team/index.html**

還是偶爾不會自動轉址問題能解決 lol?
不確定網路差的情況下js還沒載完 就去點`/2020/team/` 導致?

**Comment by sheiun** [comment]
提供一個較粗糙的解決方法直接把 `routes.ts` 中的 `path: '/team'` 直接改成 `path: /team/staff` 就可以避免這種情況

**Comment by chenyunchen** [comment]
好主意 那golangconf 這邊我先這樣改
