### ISSUE TITLE
<del></del>標籤未被正確顯示

### ISSUE THREAD

**Issue by ianchen0119** [sitcon-tw/2020#26]
[連結](https://sitcon.org/2020/team/staff)
請參見文創組的介紹，其中`<del>`並未被正確顯示為刪除線（原本應該長這樣（？））：
> 負責年會主視覺設計、網站設計、相關紀念品發想<del>挖坑</del>等事宜，開場動畫與許多會場內的印刷品也都是由文創組設計。

實際上用檢查工具查看HTML源碼會顯示：
> <p class="paragraph staff-group-intro">負責年會主視覺設計、網站設計、相關紀念品發想&lt;del&gt;挖坑&lt;/del&gt;等事宜，開場動畫與許多會場內的印刷品也都是由文創組設計。</p>

**Comment by chiuhans111** [comment]
@ianchen0119 你好，我是文創組的組員火柴
很高興你細心觀賞我們設計的網頁，在你提到的問題中

> \<del>挖坑\</del>

是刻意設計為不被解讀的喔~

**Comment by ianchen0119** [comment]
好的XDD
